apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
data:
  password: YWJvYnVz  # echo -n "yourpassword" | base64

---
apiVersion: v1
kind: Secret
metadata:
  name: fastapi-secrets
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOmFib2J1c0Bwb3N0Z3Jlcy1zZXJ2aWNlOjU0MzIvZXhhbXBsZQ== # добавьте ваши секреты для FastAPI в base64

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fastapi-config
data:
  # добавьте ваши конфигурационные переменные для FastAPI